services:
  mysql:
    image: mysql:8.0
    container_name: job-fit-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: job_fit_analyzer
      MYSQL_USER: job_fit_user
      MYSQL_PASSWORD: job_fit_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: job-fit-backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/vendor:/var/www/html/vendor
      - ./backend/storage:/var/www/html/storage
    env_file:
      - ./backend/.env
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: ${APP_KEY:-base64:$(openssl rand -base64 32)}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: job_fit_analyzer
      DB_USERNAME: job_fit_user
      DB_PASSWORD: job_fit_password
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: job-fit-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

volumes:
  mysql_data:
